### ISSUE TITLE
Windows下怎么部署？

### ISSUE THREAD

**Issue by asan2006** [walkor/live-camera#2]
一直折腾不好，求详细教程。

**Comment by walkor** [comment]
1、下载 或者 git clone https://github.com/walkor/live-camera

2、进入到live-camera目录，运行 composer require workerman/workerman-for-win
composer安装及用法可自行百度

3、cmd命令行 cd 到live-camera目录，运行 ```php start_web.php start_worker.php```
如果出现类似"php不是内部或外部命令"的提示，说明没有设置好php环境变量，
参考 http://www.workerman.net/windows 中的动画设置环境变量

**Comment by simpleDgq** [comment]
![error](https://cloud.githubusercontent.com/assets/22284124/21668787/195bced4-d340-11e6-8999-8856b949c932.png)
运行 php start_web.php start_worker.php的时候出现这个错误是为什么啊？

**Comment by walkor** [comment]
没加载vendor/autoload.php
重新下载一份live-camera试下

**Comment by simpleDgq** [comment]
![error](https://cloud.githubusercontent.com/assets/22284124/21672116/0176efae-d35b-11e6-8872-08db7a8ffb4d.png)
重新下载这个live-camera试了一下，然后报了这个错误，然后我删除了原先的workerman文件夹，只留下了workerman-for-win这个文件夹，就可以运行了，不知道是为什么。

**Comment by walkor** [comment]
用错版本了，你windows系统用了linux版本的workerman。

**Comment by simpleDgq** [comment]
非常感谢，这回复真的是快，哈哈。

**Comment by liuzhen153** [comment]
手机端怎样实现直播呢？您的例子http://www.workerman.net/demos/live-camera/camera.html在手机端打开了并不能使用。请问有没有手机端H5直播的实现呢？
