### ISSUE TITLE
部署到CentOS服务器环境下无法观看

### ISSUE THREAD

**Issue by xiaoyangLee** [walkor/live-camera#4]
本地虚拟机CentOS 7，部署到服务器中时，关闭防火墙可以正常直播和观看，但是开启防火墙甚至设置防火墙规则就不行，观看页面无法收到数据。（没有更改代码的前提下，开放了8080和8088端口）
部署到阿里云的服务器上时，就算我完全关闭了防火墙，观看页面也无法显示视频。

**Comment by walkor** [comment]
这个不是live-camera的问题，请给阿里云提工单。
