### ISSUE TITLE
index.html中chrome浏览器内存占用率问题

### ISSUE THREAD

**Issue by xiaoyangzai** [walkor/live-camera#6]
当网页通过websocket接收的图片数据，加载到img标签中时，网页内存占用率一直在增加，楼主有没有遇到这个问题，怎么解决的呢？

**Comment by walkor** [comment]
我这对前端研究不多，没有办法解决。

这里还有个视频项目可以测试下
https://github.com/walkor/workerman-webrtc

**Comment by xiaoyangzai** [comment]
已解决，就是前端中对象空间释放问题！谢谢啦
